# Generated by Django 5.0.1 on 2024-03-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_popular_destination_place_popular_destination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular_destination_place',
            name='category',
        ),
        migrations.RemoveField(
            model_name='popular_destination_image',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Popular_Destination_Category',
        ),
        migrations.DeleteModel(
            name='Popular_Destination_Image',
        ),
        migrations.DeleteModel(
            name='Popular_Destination_place',
        ),
    ]
