# Generated by Django 5.0.1 on 2024-03-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_package_brochure_pdf_package_itinerary_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='The_World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='The_World')),
                ('name', models.CharField(max_length=100)),
                ('Discount_Percentage', models.PositiveIntegerField()),
                ('Itinerary_link', models.URLField(default='/')),
            ],
        ),
        migrations.AddField(
            model_name='popular_destination',
            name='Itinerary_link',
            field=models.URLField(default='/'),
        ),
    ]
