# Generated by Django 5.0.1 on 2024-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
